import { useMemo } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, FileText, Link as LinkIcon } from "lucide-react";
import { Card } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { useUserContext } from "../lib/user-context";

type ProjectTask = {
  id: number;
  title: string;
  description: string;
  ownerType: string;
  status: string;
  assigneeUserId?: number | null;
  workflowStepId: number | null;
};

type WorkflowStep = {
  id: number;
  name: string;
};

type ManagementData = {
  tasks: ProjectTask[];
  workflowSteps: WorkflowStep[];
};

type Deliverable = {
  id: number;
  stepId: number;
  title: string;
  version: number;
  createdAt: string;
};

export default function TaskDetail() {
  const { id, taskId } = useParams<{ id: string; taskId: string }>();
  const projectId = Number(id);
  const taskIdNumber = Number(taskId);
  const navigate = useNavigate();
  const { users } = useUserContext();

  const { data: managementData } = useQuery<ManagementData>({
    queryKey: ["/api/projects", projectId, "management"],
    enabled: Number.isFinite(projectId),
  });

  const { data: deliverables = [] } = useQuery<Deliverable[]>({
    queryKey: ["/api/projects", projectId, "deliverables"],
    enabled: Number.isFinite(projectId),
  });

  const task = useMemo(() => {
    return managementData?.tasks.find((t) => t.id === taskIdNumber) || null;
  }, [managementData?.tasks, taskIdNumber]);

  const workflowStep = useMemo(() => {
    if (!task?.workflowStepId) return null;
    return managementData?.workflowSteps.find((step) => step.id === task.workflowStepId) || null;
  }, [managementData?.workflowSteps, task?.workflowStepId]);

  const assigneeName = useMemo(() => {
    if (!task?.assigneeUserId) return "Unassigned";
    return users.find((u) => u.id === task.assigneeUserId)?.name ?? "Unassigned";
  }, [task?.assigneeUserId, users]);

  const relatedDeliverables = useMemo(() => {
    if (!task?.workflowStepId) return [] as Deliverable[];
    return deliverables.filter((d) => d.stepId === task.workflowStepId);
  }, [deliverables, task?.workflowStepId]);

  if (!task) {
    return (
      <Card className="p-6">
        <div className="text-sm text-muted-foreground">Task not found.</div>
        <Button variant="outline" size="sm" className="mt-4" onClick={() => navigate(-1)}>
          <ArrowLeft className="h-4 w-4 mr-1" />
          Back
        </Button>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-start justify-between gap-4">
        <div>
          <Button variant="ghost" size="sm" className="mb-2" onClick={() => navigate(-1)}>
            <ArrowLeft className="h-4 w-4 mr-1" />
            Back to network
          </Button>
          <h1 className="text-2xl font-bold text-foreground">{task.title}</h1>
          <p className="text-sm text-muted-foreground mt-1">{task.description || "No description"}</p>
        </div>
        <Badge variant="secondary">{task.status.replace(/_/g, " ")}</Badge>
      </div>

      <Card className="p-5">
        <div className="grid gap-4 md:grid-cols-2">
          <div>
            <div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Owner</div>
            <div className="mt-1 text-sm text-foreground">
              {task.ownerType === "agent" ? "Agentic workflow" : "Human"}
            </div>
          </div>
          <div>
            <div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Assignee</div>
            <div className="mt-1 text-sm text-foreground">{assigneeName}</div>
          </div>
          <div>
            <div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Workflow step</div>
            <div className="mt-1 text-sm text-foreground">{workflowStep?.name || "None"}</div>
          </div>
        </div>
      </Card>

      <Card className="p-5">
        <div className="flex items-center justify-between gap-3">
          <div>
            <div className="text-sm font-semibold text-foreground">Completed deliverables</div>
            <p className="text-xs text-muted-foreground">Deliverables generated by this task’s workflow step.</p>
          </div>
          {workflowStep && (
            <Button variant="outline" size="sm" onClick={() => navigate(`/project/${projectId}/workflow/${workflowStep.id}`)}>
              <LinkIcon className="h-4 w-4 mr-1" />
              Open workflow step
            </Button>
          )}
        </div>

        {relatedDeliverables.length === 0 ? (
          <div className="mt-4 text-sm text-muted-foreground">No deliverables yet.</div>
        ) : (
          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">
            {relatedDeliverables.map((deliverable) => (
              <Card key={deliverable.id} className="p-3">
                <div className="flex items-start gap-2">
                  <FileText className="h-4 w-4 text-primary" />
                  <div className="min-w-0">
                    <div className="text-sm font-semibold text-foreground truncate">{deliverable.title}</div>
                    <div className="text-xs text-muted-foreground">v{deliverable.version}</div>
                    <div className="text-xs text-muted-foreground">{new Date(deliverable.createdAt).toLocaleString()}</div>
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </Card>
    </div>
  );
}
